# <a id='toc1_'></a>[Pandas](#toc0_)
- # Pandas is a way to manipulate data of csv

- ## Basics:
```
import pandas as pd
```
<b style = "color:black; background:LightGreen">
var = pd.read_csv() ; it can read both csv and url

TYPE: type(var)
</b>

- ### Type Dataframe means a 2D grid with row and column
<br><br>

In [3]:
import pandas as pd
iris = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")
print(type(iris))

<class 'pandas.core.frame.DataFrame'>


- ## Parameters
- ### Copy:  <b style = "color:black;background:LightGreen"> panda_var.copy() </b>
- ### head: It gives brief idea about how the data looks like , <b style = "color:black;background:LightGreen"> panda_var.head() [by default it will show 5]</b>
- ### <b style = "color:black;background:orange"> panda_var.copy(n) , to show n tuples </b>
![image.png](attachment:image.png)

- ### shape: <b style = "color:black;background:White"> var_panda.shape , </b> To find out row and column ,
####     output shows rows column

- ### dtypes: <b style = "color:black;background:LightGreen"> var_panda.dtypes </b>

- ### All columns: <b style = "color:black;background:orange"> var_panda.columns , To find out columns. </b>

- ### Specific_column: <b style = "color:black;background:orange"> var_panda.columnName /<b style = "color:black;background:white">var_panda["columnName]</b>  , To find out particular column. </b>

1. #### Changing Column Names: <b style = "color:black;background:orange"> df.columns = ['x' , 'y' , 'z'] </b>

- ### describe: <b style = "color:black;background:white"> var_panda.describe </b>
1. ##### Describe is used to view some basic statistical details like percentile, mean, std etc. of a data frame or a series of numeric values.

#### <b style = "color:black;background:orange">Problem: It excludes the NULL values </b>

- ### isnull() : <b style = "color:black;background:white"> var_panda.isnull()[No print] </b>&nbsp; It is used to check for NULL entry
#### <b style = "color:black;background:LightGreen"> Best way to show the sum of all the Null Entries of a Column </b> <br>
#### <b style = "color:black;background:yellow"> var_panda.isnull().sum() </b>

- ### Finding Out Spefic Entry [Row x to y , Column m to n]
#### <b style = "color:black;background:white">var_panda.iloc[x:y , m:n]

In [4]:
import pandas as pd
iris = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")
df = iris.copy()
df.head(3)

print(df.shape)
print(df.dtypes)
print(df.columns)

df.columns = ['sl', 'sw', 'pl', 'pw', 'flower_type']
print("\n")
print(df.describe()) #DBP_NOTES Best tool to describe the data

print("\n")
print("Specific Column Access")
print(df.flower_type)
print(df['flower_type']) #Same as previous

print("In dealing with NULL values , we have to option")
df.isnull()

print("Best way to show the sum of all Null values in each column")
df.isnull().sum()

print("To access Particular Entry , Using Slices\n")
print("Accessing Column 2 to 4 and Row 1 to 3\n")
df.iloc[1:4 , 2:5]

(149, 5)
5.1            float64
3.5            float64
1.4            float64
0.2            float64
Iris-setosa     object
dtype: object
Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')


               sl          sw          pl          pw
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000


Specific Column Access
0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
144    Iris-virginica
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
Name: flower_type, Length: 149, dtype: o

pl   pw  flower_type
1  1.3  0.2  Iris-setosa
2  1.5  0.2  Iris-setosa
3  1.4  0.2  Iris-setosa

- ## Manipulating Data in Dataframe
![image.png](attachment:image.png)

- ### Deleting Tuple: <b style = "color:black;background:LightGreen"> var_panda.drop(Nth row) : It means not remove nth row , rather Remove the row <i>with label n</i></b>
#### <b style = "color:black;background:white"> It does not manipulate the original table , rather it creates a separate table without the dropped tuple</b>

#### To show change:

    ```
        a = var_panda.drop(n)  
        print(a.head())
    ```

#### Deleting Multiple tuples:
    
##### ``` var_panda.drop[ [m,n] ] , here m,n are labels. ```
#### <b style = "color:black;background:yellow"> To show change in original </b>
##### ``` var_panda.drop(n , inplace = True) ```
<br><br>

- ### Accessing the labels : <b style = "color:black;background:white"> var_pandas.index() </b>

#### Specific index:
##### ``` var_panda.index[n] ```
<br><br>

### Logical Operations on Rows and Columns
- #### Checking a Column Values logical(>,<,=) :
##### ``` var_panda.ColumnName > / < / =  value ```

- #### Checking the Row Values for a specific Column logical(>,<,=) :
##### ``` var_panda[var_panda.column > / < / = value] ```

- #### Adding a Row  
- <b style = "color:black;background:white">  [iloc] -->  <b style = "color:black;background:yellow"> it works positionwise</b> </b>
- <b style = "color:black;background:white">  [loc] -->  <b style = "color:black;background:yellow"> it works labelwise</b> </b>

##### ``` var_panda.iloc[3] ``` --> <b style = "color:black;background:white"> It returns all the position details of a row </b>


##### <b style = "color:black;background:white">&nbsp;To Add a Row </b> ``` df.loc[label] = [data1 , data2 , data3 , ... , dataN] ```
##### <b style = "color:black;background:yellow"> It is added in the tail , var_panda.tail

<br>
    ### Resetting an Index <b style = "color:black;background:yellow"> level</b>

    #### ``` var_panda.reset.index(drop = True, inplace = True) ```

 ### Deleting a Column [axis = 1 means locate columnwise]
- ### Creating a copy without dlt column : - ## Manipulating Data in Dataframe
![image.png](attachment:image.png)

- ### Deleting Tuple: <b style = "color:black;background:LightGreen"> var_panda.drop(Nth row) : It means not remove nth row , rather Remove the row <i>with label n</i></b>
#### <b style = "color:black;background:white"> It does not manipulate the original table , rather it creates a separate table without the dropped tuple</b>

#### To show change:

    ```
        a = var_panda.drop(n)  
        print(a.head())
    ```

#### Deleting Multiple tuples:
    
##### ``` var_panda.drop[ [m,n] ] , here m,n are labels. ```
#### <b style = "color:black;background:yellow"> To show change in original </b>
##### ``` var_panda.drop(n , inplace = True) ```
<br>

- ### Accessing the labels : <b style = "color:black;background:white"> var_pandas.index() </b>

#### Specific index:
##### ``` var_panda.index[n] ```
<br>

### Logical Operations on Rows and Columns
- #### Checking a Column Values logical(>,<,=) :
##### ``` var_panda.ColumnName > / < / =  value ```

- #### Checking the Row Values for a specific Column logical(>,<,=) :
##### ``` var_panda[var_panda.column > / < / = value] ```

- #### Adding a Row  
- <b style = "color:black;background:white">  [iloc] -->  <b style = "color:black;background:yellow"> it works positionwise</b> </b>
- <b style = "color:black;background:white">  [loc] -->  <b style = "color:black;background:yellow"> it works labelwise</b> </b>

##### ``` var_panda.iloc[3] ``` --> <b style = "color:black;background:white"> It returns all the position details of a row </b>


##### <b style = "color:black;background:white">&nbsp;To Add a Row </b> ``` df.loc[label] = [data1 , data2 , data3 , ... , dataN] ```
##### <b style = "color:black;background:yellow"> It is added in the tail , var_panda.tail

<br>
    ### Resetting an Index <b style = "color:black;background:yellow"> level</b>

    #### ``` var_panda.reset.index(drop = True, inplace = True) ```

 ### Deleting a Column [axis = 1 means locate columnwise]
- ### Creating a copy without dlt column :
    <b style = "color:black;background:white">
    ####  ``` var_panda.drop(<b>colmn_name</b>, <b style = "color:black;background:yellow">axis = 1 </b> ```

- ### originally dlting column :
    <b style = "color:black;background:white">
    ####  ``` var_panda.drop(<b>colmn_name</b>, <b style = "color:black;background:yellow">axis = 1 </b>, <b>inplace=True)```

In [5]:
import pandas as pd
iris =pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")
df = iris.copy()
df.columns = ['sl', 'sw', 'pl', 'pw', 'flower_type']
print("Using df.drop(0)")
df.drop(0)

print("#Here the original data is not changed , a copy of the data is changed with the drop function")
print(df.head() )

print("\nTo show the change , storing the drop function in a variable")
change = df.drop(0)
print(change.head())

print("\n\nTo show change in original data , we have to use inplace = True")
df.drop(0, inplace = True)
print(df.head())

print("\nTo show the all the labels")
df.index

print(df.index[0])


print("\nTo drop the first two rows[label 0 and 1]")
df.drop(df.index[ [0,1] ], inplace = True)
df.head()


print("\n Logical Operation on column")
print(df.sl > 5)

print("\n Rows of Column sl > 5")
print(df[df.sl > 5])

print("\n Rows of flower_type == 'Iris-setosa'")
print(df[df.flower_type == 'Iris-setosa'])


print("\n Description of the Rows of flower_type == 'Iris-setosa \n")
df[df.flower_type == 'Iris-setosa'].describe()

print("\n Head \n" , df.head())
print("\n iloc[0] \n" , df.iloc[0])
#print("\n loc[0]" , df.loc[0]) #DBP_NOTES error as there is no label 0

df.loc[0] = [1 ,2 ,3 ,4 , 'Iris-setosa']
print(df.tail())

Using df.drop(0)
#Here the original data is not changed , a copy of the data is changed with the drop function
    sl   sw   pl   pw  flower_type
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

To show the change , storing the drop function in a variable
    sl   sw   pl   pw  flower_type
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa


To show change in original data , we have to use inplace = True
    sl   sw   pl   pw  flower_type
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa

To show the all the labels
1

To drop the first two rows[label 0 and 1]

 Logical Operation on column
3      False
4       True
5 

In [16]:
import pandas as pd
from IPython.display import display, HTML
iris =pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")
df = iris.copy()


display(HTML("<strong>\n Column Operations</strong>"))
df.columns = ['sl', 'sw', 'pl', 'pw', 'flower_type']
print("Using df.drop(0)")
df.drop(0)

print("#Here the original data is not changed , a copy of the data is changed with the drop function")
print(df.head() )

print("\nTo show the change , storing the drop function in a variable")
change = df.drop(0)
print(change.head())

print("\n\nTo show change in original data , we have to use inplace = True")
df.drop(0, inplace = True)
print(df.head())

print("\nTo show the all the labels")
df.index

print(df.index[0])


print("\nTo drop the first two rows[label 0 and 1]")
df.drop(df.index[ [0,1] ], inplace = True)
df.head()


print("\n Logical Operation on column")
print(df.sl > 5)

print("\n Rows of Column sl > 5")
print(df[df.sl > 5])

print("\n Rows of flower_type == 'Iris-setosa'")
print(df[df.flower_type == 'Iris-setosa'])


print("\n Description of the Rows of flower_type == 'Iris-setosa \n")
df[df.flower_type == 'Iris-setosa'].describe()

print("\n Head \n" , df.head())
print("\n iloc[0] \n" , df.iloc[0])
#print("\n loc[0]" , df.loc[0]) #DBP_NOTES error as there is no label 0

df.loc[0] = [1 ,2 ,3 ,4 , 'Iris-setosa']
print(df.tail())


print("\n Resetting Index[var.reset_index(),\n")
df.reset_index(drop = True, inplace = True)
df.head()
display(HTML("<strong>\n Deleting a column , But not original</strong>")) #DBP_HIGHLIGHTES well by using df.drop('sl',  axis = 1) , it will not delete the original column
df.drop('sl',  axis = 1)
df.head()


display(HTML("<strong>\n Deleting a column but original</strong>"))
df.drop('sl' , axis=1 , inplace = True)
df.head()
df.describe()


display(HTML("<strong>\n Standard Way: del </strong> var_panda['col_name]"))
del df['sw']
df.head()
df.describe()


display(HTML("<strong>\n Adding a column</strong>"))
display(HTML("<strong>\n Syntax: var_panda['new_col_name'] = value</strong>"))
display(HTML("<strong>\n A column that gives the difference of pl and pw</strong>"))
df["diff_pl_pw"] = df["pl"] - df["pw"]
df.head()




Using df.drop(0)
#Here the original data is not changed , a copy of the data is changed with the drop function
    sl   sw   pl   pw  flower_type
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

To show the change , storing the drop function in a variable
    sl   sw   pl   pw  flower_type
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa


To show change in original data , we have to use inplace = True
    sl   sw   pl   pw  flower_type
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa

To show the all the labels
1

To drop the first two rows[label 0 and 1]

 Logical Operation on column
3      False
4       True
5 

pl   pw  flower_type  diff_pl_pw
0  1.4  0.2  Iris-setosa         1.2
1  1.7  0.4  Iris-setosa         1.3
2  1.4  0.3  Iris-setosa         1.1
3  1.5  0.2  Iris-setosa         1.3
4  1.4  0.2  Iris-setosa         1.2

In [39]:
import numpy as np
import pandas as pd
from IPython.display import display, HTML
iris =pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")
df = iris.copy()
df.columns = ['sl', 'sw', 'pl', 'pw', 'flower_type']

display(HTML("<strong style='color:white;background:black'>\n Handling Column with NaN[Not a Number] Entries</strong>"))

display(HTML("<strong style='background:yellow:'>\n Creating Nan Entries ; np.nan</strong>"))
df.iloc[2:4 , 1:3] = np.nan
print(df.head())

df.describe()

display(HTML("<strong>\n Method1: Dropping the nan : df.dropna(inplace=True)</strong>"))
dropna=df.dropna()
print(dropna) 

display(HTML("<strong style='background:black;color:white'>\n Method2: Filling the nan with the mean of corresponding column :\n df.colname.fillna(df. colname.mean())</strong>"))
df.sw.fillna(df.sw.mean() , inplace=True)
df.pl.fillna(df.pl.mean() , inplace=True)
df.head()


display(HTML("<strong style='background:black;color:white'>\n Handling Strings in Columns(Y/N)</strong>"))
df["Gender"] = "Female" #DBP_NOTES Adding a new Column
df.iloc[0:5 , 5] = "Male" #DBP_NOTES Changing the values of first 5 rows of 6th columns to Male
print(df.head())
print(df.tail())

display(HTML("<strong style='background:black;color:white'>\n Changing the string into numeric 0/1 using a function</strong>"))
def f(s) :
    if s == "Male":
        return 0
    else:
        return 1

df["Sex"] = df.Gender.apply(f)
print(df.head())
print(df.tail())

display(HTML("<strong style='background:black;color:white'>\n After changing to Numeric , deleting the Gender Column to remover redaundency , as it is converted to Sex Column</strong>"))
del df["Gender"]
print(df.head())

    sl   sw   pl   pw  flower_type
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  NaN  NaN  0.2  Iris-setosa
3  5.0  NaN  NaN  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa


      sl   sw   pl   pw     flower_type
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
5    4.6  3.4  1.4  0.3     Iris-setosa
6    5.0  3.4  1.5  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[147 rows x 5 columns]


C:\Users\panth\AppData\Local\Temp\ipykernel_8672\1364618021.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.sw.fillna(df.sw.mean() , inplace=True)
C:\Users\panth\AppData\Local\Temp\ipykernel_8672\1364618021.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, w

    sl        sw        pl   pw  flower_type Gender
0  4.9  3.000000  1.400000  0.2  Iris-setosa   Male
1  4.7  3.200000  1.300000  0.2  Iris-setosa   Male
2  4.6  3.046939  3.806122  0.2  Iris-setosa   Male
3  5.0  3.046939  3.806122  0.2  Iris-setosa   Male
4  5.4  3.900000  1.700000  0.4  Iris-setosa   Male
      sl   sw   pl   pw     flower_type  Gender
144  6.7  3.0  5.2  2.3  Iris-virginica  Female
145  6.3  2.5  5.0  1.9  Iris-virginica  Female
146  6.5  3.0  5.2  2.0  Iris-virginica  Female
147  6.2  3.4  5.4  2.3  Iris-virginica  Female
148  5.9  3.0  5.1  1.8  Iris-virginica  Female


    sl        sw        pl   pw  flower_type Gender  Sex
0  4.9  3.000000  1.400000  0.2  Iris-setosa   Male    0
1  4.7  3.200000  1.300000  0.2  Iris-setosa   Male    0
2  4.6  3.046939  3.806122  0.2  Iris-setosa   Male    0
3  5.0  3.046939  3.806122  0.2  Iris-setosa   Male    0
4  5.4  3.900000  1.700000  0.4  Iris-setosa   Male    0
      sl   sw   pl   pw     flower_type  Gender  Sex
144  6.7  3.0  5.2  2.3  Iris-virginica  Female    1
145  6.3  2.5  5.0  1.9  Iris-virginica  Female    1
146  6.5  3.0  5.2  2.0  Iris-virginica  Female    1
147  6.2  3.4  5.4  2.3  Iris-virginica  Female    1
148  5.9  3.0  5.1  1.8  Iris-virginica  Female    1


    sl        sw        pl   pw  flower_type  Sex
0  4.9  3.000000  1.400000  0.2  Iris-setosa    0
1  4.7  3.200000  1.300000  0.2  Iris-setosa    0
2  4.6  3.046939  3.806122  0.2  Iris-setosa    0
3  5.0  3.046939  3.806122  0.2  Iris-setosa    0
4  5.4  3.900000  1.700000  0.4  Iris-setosa    0


In [15]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

FileNotFoundError: [Errno 2] No such file or directory: 'attack.csv'

In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0


# Size of Elements in Numpy array.

1.  <b>One integer needs 28 bytes
2.  <b>One elements takes 4 bytes


In [ ]:
#Size of one element in numpy array

print(np_arr.itemsize) # itemize means size of one element in array

## Size of 100 elements in numpy array
print(np_arr.itemsize * np_arr.size) # size of 100 elements in array

4
400


In [ ]:
#DBP_HIGHLIGHTES Size of Integer in array using Numpy
#- sys.getsize() is used to get the size of integer in array
import sys

## Size of one element in list

a = 10
print(sys.getsizeof(a)) # size of one element in list

## Size of 100 elements in list
print(sys.getsizeof(a) * len(li_arr)) # size of 100 elements in list



28
2800


# Time Execution (Numpy Faster than Array)

1. t1 means start time and t2 means end time
2. <i>function defition format is <p style="color:yellow">def function_name():</p> </i>
3.  Difference between rang() and np.arange() is that range() is used in list and np.arange() is used in numpy array

4. Storing function values in variable
  <ul style="color:yellow">
  <li>t_list = addition_using_list()</li>
  <li>t_numpy = addition_using_numpy() </li>
  </ul>

In [ ]:
import time #DBP_HIGHLIGHTES time is used to get the time of execution of code
import numpy as np

size = 1000000

def addition_using_list():
    t1 = time.time() #time.time() means current time.
    a = range(size)
    b = range(size)
    c = [ a[i] + b[i] for i in range(size)]
    t2 = time.time()
    return t2 - t1

    #DBP_NOTES here t1 means start time and t2 means end time

def addition_using_numpy():
    t1 = time.time()
    a = np.arange(size)
    b = np.arange(size)
    c = a + b
    t2 = time.time()
    return t2 - t1

t_list = addition_using_list()
t_numpy = addition_using_numpy()

print("List Time: ", t_list * 1000)
print("Numpy Time: ", t_numpy * 1000)






List Time:  0.3135261535644531
Numpy Time:  0.00500178337097168


# Creating Numpy Array List
- <b>type</b> means it will show the type of variable

- difference between np.array and np.arange is that <p style="color:yellow"> np.array is used to convert list into array and np.arange is used to create array of range of numbers </p>

- numpy array only contain homogenous elements
like it convert all elements into string when dealing with string , int , float

-<span>np.array(array , <p style="color:yellow"> dype=str</p> is used to set the type)</span>

-  np.array( <b> array * 3 </b> is used to repeat the array 3 times)

In [ ]:
import numpy as np

a = [1, 2, 3, 4 , 'a' , "DBP"]
b = np.array(a)
print(b)
print(type(b))


print(np.array(a * 3 , dtype=object)) #DBP_HIGHLIGHTES dtype=object is used to store the data in array as object

['1' '2' '3' '4' 'a' 'DBP']
<class 'numpy.ndarray'>
['1' '2' '3' '4' 'a' 'DBP' '1' '2' '3' '4' 'a' 'DBP' '1' '2' '3' '4' 'a'
 'DBP']


# Some Numpy functions

<p style="color:black;background:white">
It is not necessary to indicate print
as like<br>
b = something <br>
b <br>
then b will be printed
</p>

1. <p style = "color:yellow">np.ones(): np.ones is used to <b><i>create an array of 1's</i>.

<b>Syntax</b><hr>
<p style="color:black;background:white">by default the type is float,</n>
For example: np.ones(5) means 1. , 1. , 1. , 1. , 1.
<ul style="color:black;background:yellow">
<li> np.ones(size) </li>
<li>np.ones(dim1 , dim2) // here np.zeroes(2,3) means an array[2][3] </li>
<li>np.ones(size , dtype = str)</li>
</ul>
</p>

2. <p style = "color:yellow">np.zeroes()
<b>Syntax</b><hr>
<p style="color:black;background:white">by default the type is float,</n>
For example: np.zeroes(5) means 0. , 0. , 0. , 0. , 0.
<ul style="color:black;background:yellow">
<li> np.zeroes(size) </li>
<li>np.zeroes(dim1 , dim2) // here np.zeroes(2,3) means an array[2][3] </li>
<li>np.zeroes(size , dtype = str)</li>
</ul>
</p>


3. <p style = "color:yellow">np.full()</p>
 - <p style="color:black;background:white">syntax: np.full(size , value)</p>
  it creates
  an array of size <p style="background:black">size</p>
  with elements given in <p style="background:black">value</p>
  
4. <b style="color:yellow">np.arange</b> <p style="color:black;background:white"> Return evenly spaced value with given interval </p>

<b>syntax</b>: `` np.arange(start, end, step) / `` <p style="color:black;background:yellow">np.arange(end)[here step will be 1]</p>

5. <b style="color:yellow">np.linspace</b> <p style="color:black;background:white"> Step is optional , by default 50 samples will be generated</p> `` np.linspace(start, end)``

6. <b>syntax</b>: ``np.linspace(start , end , num_samples) ``

<p style="color:black;background:white">np.linspace(start , end , num_samples , endpoint = False) If True, stop is the last sample. Otherwise, it is not included. Default is True.</p>

7. <b style="color:yellow">np.identity(num)</b> <p style="color:black;background:white">Creates an identity matrix of num * num</p>

<b style="color:yellow">np.identity(M * N)</b> <p style="color:black;background:white">Creates an identity matrix of M * N</p>

8. <b style="color:yellow">np.random.rand(size)*limit
<p style="color:black;background:white">
From 0 to 10 , np.random.rand(10)*10

<b style="color:yellow">np.random.randint<i>(lower_bound , upper_bound , size)</i>
<p style="color:black;background:white">From m to n , np.random.randint(m , n , size=(n-m+1))




In [ ]:
import numpy as np
b = np.ones(5)  #syntax: np.ones(size)
print(b)

br = np.zeros((2,3) , dtype=int)  #syntax: np.zeros(size)
print(br)


fl = np.full((2,3) , 5) #syntax: np.full(size , value)
print(fl)

empty = np.empty((2,3)) #syntax: np.empty(size)
print(empty)

arange = np.arange(0, 10, 2) #syntax: np.arange(start, end, step)
print(arange)

arange1 = np.arange(10) #syntax: np.arange(end)
print(arange1)

linespace = np.linspace(0 , 10) #
print(linespace)

#To find out the step value
print("The difference between 2nd and 1st sample:" , linespace[1] - linespace[0])
print("The difference between 3rd and 2nd sample:" , linespace[2] - linespace[1])

linespace1 = np.linspace(0 , 10 , 5) #syntax: np.linspace(start, end, number of samples)
print(linespace1)

linespace_endpoint = np.linspace(0 , 10 , 5 , dtype=int , endpoint=False) #syntax: np.linspace(start, end, number of samples, endpoint=False)
print(linespace_endpoint)

identity_matrix = np.identity(5 , dtype=int)
print(identity_matrix)

iden_matr_m_n = np.eye(3,5)
print(iden_matr_m_n)

rand = np.random.rand(3) #Creates array of random value
print(rand)

rand2D = np.random.rand(2,3)
rand2D


#Random sample from 0 to 10
randlimit = np.random.rand(10)*10
randlimit

randint = np.random.randint(2,10 , size=10)
randint


[1. 1. 1. 1. 1.]
[[0 0 0]
 [0 0 0]]
[[5 5 5]
 [5 5 5]]
[[1.23423175e-311 1.23423175e-311 1.23423175e-311]
 [1.23423175e-311 1.23423175e-311 1.23423175e-311]]
[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
The difference between 2nd and 1st sample: 0.20408163265306123
The difference between 3rd and 2nd sample: 0.20408163265306123
[ 0.   2.5  5.   7.5 10. ]
[0 2 4 6 8]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1

array([5, 6, 7, 5, 3, 4, 5, 5, 3, 7])

# Some Numpy Functions V 2.0

## Some Array Properties:
### print must be used
- <b>array.data</b> <i>[Provides Memory Location]</i>
- <b>array.shape</b> <i>[Provides Size]</i>
- <b>array.dtype</b> <i>[Provides datatype]</i>
- <b>array.strides</b> <i>[Provides bytes for moving one elem to another]</i>

1. <b>2d array declare<b> <i>arr = [ [x,y,z] , [m,n,p] ....]</i>
  - <b>then converting it to numpy</b> , <i>np_2d = np.array(arr)</i>

### Indexing & Slicing
- after storing arr[100] to x = np.array(arr)
- then ``` print(x[1:5]) printing 2nd to 5th element ``` <br><br>
  <b style="color:yellow">Accessing 2d index</b>
  <p style="color:black;background:white">
 For 2D array , <b>Slicing</b> <br>
  &nbsp;&nbsp; 0 1 2 3 <br>
  0  1 2 3 4 <br>
  1  5 6 7 8 <br>
  2  9 10 11 12 <br>
  3  13 14 15 16 <br>
<br>
<i>Accessing 5,6,7</i> <br>
``` Row = 1 , Column = 0 to 2+1 ```
``` print(np_2d[1 , :3]) , by default start with 0 , so 0:3 = :3 ``` <br>
<i>Accessing:</i> <br>
5,6,7 <br>
9,10,11 <br>
13,14,15 <br>
``` np_2d[1:4 , :3] ```




In [ ]:
li_2d = [ [1,2,3,4] , [5,6,7,8] , [9,10,11,12] , [13,14,15,16] ]
#Here it is
#    0 1 2 3
# 0  1 2 3 4
# 1  5 6 7 8
# 2  9 10 11 12
# 3  13 14 15 16


li = [1,2,3,4,5,6]
np_2d = np.array(li_2d)
np_li = np.array(li)
print(np_2d.data)
print(np_2d.shape)
print(np_2d.dtype)
print(np_2d.strides)

print(li[0:3]) # 1:3 means 1st row to 3rd row

#Accessing 5,6,7
#row = 1 , col = 0 to 3
print(np_2d[1 , :3])

#Accessing 4 , 8 , 12
# Row = 0 to 2 , Col = 3
print(np_2d[:3 , 3])

#DBP_NOTES Careful not [0:3][2] , it will give 9,10,11,12


#DBP_HIGHLIGHTES Accessing 5,6,7 9,10,11 13,14,15
print(np_2d[1:4 , :3])


(4, 4)
int32
(16, 4)
[1, 2, 3]
[5 6 7]
[ 4  8 12]
[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


# Mathematical Operations on Numpy
- ## Incrementing elements in list
###  <b style = "color:black; background:yellow"> li = [i+1 for i in li] </b>

- ## Incrementing elements in Numpy [np_li = np.array(li)]
###  <b style = "color:black; background:yellow"> np_li = np_li+1 </b>
###  <b style = "color:black; background:yellow"> Adding two vectors: <br> a = np.li...() , b = np.li(...)   ,   c = a+b </b>

<br><br>
### <b style = "color:black; background:white">Array Summation          : ara.sum()   </b>
### <b style = "color:black; background:white">Array Average            : ara.means() </b>
### <b style = "color:black; background:white">Array Minimum            : ara.min() </b>
### <b style = "color:black; background:white">Index of minimum element : ara.argmin() </b>

- ## Some logical Operations of two np_array
 ### <b style = "color:black; background:white">Suppose one np_array is np_li , 2nd is np_li1 </b>
  
  1. #### <b style = "color:black; background:white">np_li '<' / '>' / '==' / ' np_li`1</b>
  2. #### <b style = "color:black; background:white">print(np.logical_or( np_li  , np_li1) , <p style="color:black;background:yellow">must use print</p> </b>



In [ ]:
import numpy as np
li = [1,2,3,4,5,6]
li1 = [7 , 3 , 9 , 5 , 11 , 7]
a = np.random.randint(1 , 20 , 5)
b= np.random.randint(1 , 20 , 5)
np_li = np.array(li)
np_li1 = np.array(li1)


li = [i+1 for i in li]
print(li)

np_li = np_li + 1
print(np_li)

print('\n')
print("Random from 1 to 20" , a)
print("Random from 1 to 20" , b)
print('\n')
print("Addition of 2 arrays" , a + b)
print("Subtraction of 2 arrays" , a - b)
print("Multiplication of 2 arrays" , a * b)
print("Division of 2 arrays" , a / b)
print("Power of 2 arrays" , a ** b)

print('\n')
print(np_li.sum())
print(np_li.mean())
print(np_li.min())
print(np_li.argmax())

print("Logical Operations on array\n")
print(np_li)
print(np_li1)

np_li > np_li1
np_li == np_li1
print(np.logical_and(np_li , np_li1))
print(np.logical_or(np_li , np_li1))
print(np.logical_not(np_li))










[2, 3, 4, 5, 6, 7]
[2 3 4 5 6 7]


Random from 1 to 20 [ 1 11  8  4 15]
Random from 1 to 20 [ 5 10 13 18 19]


Addition of 2 arrays [ 6 21 21 22 34]
Subtraction of 2 arrays [ -4   1  -5 -14  -4]
Multiplication of 2 arrays [  5 110 104  72 285]
Division of 2 arrays [0.2        1.1        0.61538462 0.22222222 0.78947368]
Power of 2 arrays [        1 167620825         0         0 198698543]


27
4.5
2
5
Logical Operations on array

[2 3 4 5 6 7]
[ 7  3  9  5 11  7]
[ True  True  True  True  True  True]
[ True  True  True  True  True  True]
[False False False False False False]


# Boolean Indexing of 1D Array

- ## Extracting array based on condition (np_ara > 10)
1. ### <b style = "color:black; background:white"> bool_arr = np_ara > 10 </b>
2. ### <b style = "color:black; background:white">new_arr = np_arr[bool_arr] </b>
3. ### <b style = "color:black; background:white"> new_arr </b>

- ## Similarly using multiple conditions np_ara >10 and np_ara < 18
1. ### <b style = "color:black; background:white"> bool_arr = np_ara >10 & np_ara < 18 </b>
2. ### <b style = "color:black;background:white"> np_ara[bool_arr] </b>

- ## Converting the 0 to 3 indexed element into 101
1. ### <b style = "color:black; background:white"> new_arr = np_ara </b>
2. ### <b style = "color:black;background:white"> new_arr[:3] = 101 </b>
3. ### <b style = "color:black;background:white"> print(new_arr) </b>

- ## Converting the elements > 7 = 1011
1. ### <b style = "color:black; background:white"> new_arr = np_ara </b>
2. ### <b style = "color:black;background:white"> new_arr[new_arr > 7] = 1011 </b>
3. ### <b style = "color:black;background:white"> print(new_arr) </b>


- ## Indexes of elements where value = 100
1. ### <b style = "color:black; background:white"> new_arr = np_ara </b>
2. ### <b style = "color:black;background:white"> ind = np.where(b==100) </b>
3. ### <b style = "color:black;background:white"> print(new_arr) </b>



In [ ]:
import numpy as np


b = np.random.randint(1, 20, 8)

print(a)
print(b < 10)

#DBP_HIGHLIGHTES Accessing the elements which are less than 10
bool_arr = b < 10
new_arr = b[bool_arr]
print(new_arr)

#DBP_HIGHLIGHTES Accessing the elements which are greater than 10 but less than 15
bool_arr = (b > 10) & (b < 15)
print(b[bool_arr])

#DBP_HIGHLIGHTES Changing the elements from 0 to 3 to 101
new_arr = b ;
new_arr[:3] = 101
print(new_arr)

li3 = [1,5,3,4,5,6,7,5,9,10]
np_li3 = np.array(li3)

#converting the elements  > 7 = 1011

new_arr1 = np_li3
new_arr1[new_arr1 >= 7] = 1011
print(new_arr1)

#DBP_HIGHLIGHTES Finding index where elm = 5
ind = np.where(new_arr1 == 5)
print(ind)

a = np.array([ 't' , 'b' , 'r' , 'd' , 'e' , 'f' , 'z' , 'a'])
b1 = np.array([1,100,3,100,5,6,7,100])

#DBP_HIGHLIGHTES Finding a[i] where b1[i] == 100

ind1 = np.where(b1 == 100)
a[ind1]

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[False  True  True  True  True False False False]
[2 6 2 6]
[12 13]
[101 101 101   2   6  13  17  18]
[   1    5    3    4    5    6 1011    5 1011 1011]
(array([1, 4, 7], dtype=int64),)


array(['b', 'd', 'a'], dtype='<U1')

# Boolean Indexing of 2D Array

- ## Extracting array based on condition (np_ara > 10)
1. ### <b style = "color:black; background:white"> bool_arr = np_ara > 10 </b>
2. ### <b style = "color:black; background:white">new_arr = np_arr[bool_arr] </b>
3. ### <b style = "color:black; background:white"> new_arr </b>


- ## Indexes of elements where value = 100
1. ### <b style = "color:black; background:white"> new_arr = np_ara </b>
2. ### <b style = "color:black;background:white"> ind = np.where(b==100) </b>
3. ### <b style = "color:black;background:white"> print(new_arr) </b>

- ## Updating value of specific location
 ### Converting all 100 to 90 in 3rd Column
1. ### <b style = "color:black; background:white"> new_arr = np_ara </b>
2. ### <b style = "color:black;background:white"> ind = np.where(new_arr[: , 2] == 100) </b>
3. ### <b style = "color:black;background:white"> b[ind , 2] = 90 , <br> Careful , must pass in [ x , y] format as it is 2D array </b>



In [ ]:
import numpy as np


b = np.random.randint(1, 20, (5,6))
print(b , '\n')

bool_arr = b < 10
print(b[bool_arr] , '\n')

new_arr = b
new_arr[new_arr > 10] = 100
print(new_arr , '\n')


#DBP_HIGHLIGHTES Updating value on a specific location
ind = np.where(new_arr[: , 2] == 100)
b[ind , 2] = 90
print(b , '\n')

# b_new = np.random.randint(1 , 10 , (2,2))
# print(b_new, '\n')
# c_bool = np.array([[True , False] , [False, True] , [True,True]])
# print(c_bool)


[[11 19 15 15  9  8]
 [15 18 18  5 15  1]
 [ 6  5  1  3  4  1]
 [13  1  6  9  5  8]
 [ 9 16 19 10  2  5]] 

[9 8 5 1 6 5 1 3 4 1 1 6 9 5 8 9 2 5] 

[[100 100 100 100   9   8]
 [100 100 100   5 100   1]
 [  6   5   1   3   4   1]
 [100   1   6   9   5   8]
 [  9 100 100  10   2   5]] 

[[100 100  90 100   9   8]
 [100 100  90   5 100   1]
 [  6   5   1   3   4   1]
 [100   1   6   9   5   8]
 [  9 100  90  10   2   5]] 



# Broadcasting in Numpy
## <b style = "color:black; background:orange">It is used to perform operations on arrays of different shapes.</b>

- ## Compatibility
### 1. <b style = "color:black; background:white"> x[3,2] , y[3,2] </b>&nbsp; Perfectly Compatibile . So , + - * / ** can be possible.
<br>

### 1. <b style = "color:black; background:white">x[<i>3</i>,3] , y[<i>3</i>,2] </b>&nbsp; Not Compatibile
- ### <b style = "color:black; background:LightGreen">Solution is np.transpose(y)</b>
- ### <b style = "color:black; background:LightGreen"> np.reshape(y , (2,3) , order = 'C' / 'F' / 'A') </b>
#### <b style = "color:black; background:orange"> Careful dimension multplication should be same , [For Instance: if arr(m,n) , reshape will be (n,m)] </b>
&nbsp;
### <b style = "color:black; background:LightGreen">2. One of them is one</b> <br><br> <b style = "color:black; background:white">x[<i>3</i>,3] , y[<i>3</i>] / y[1,<i>3</i>] </b> &nbsp; Compatible . So , + - * / ** can be possible.</b>
![Image Not Found](attachment:image.png)

- ## Real Time Broadcasting
### 1. <b style = "color:black; background:LightGreen"> Before Broadcasting:</b>
![image-2.png](attachment:image-2.png)

### 2. <b style = "color:black; background:LightGreen">After Broadcasting:</b>
![image-3.png](attachment:image-3.png)
#### <b style = "color:black; background:orange"> Array of lesser shape broadcasted to fill the required , for example : [ Array 1 ] </b>



In [ ]:
import numpy as np


print("Perfectly Compatible","\n")
x= np.random.randint(1 , 10 , (3,3))
y = np.random.randint(1 , 10 , (3,3))

print(x,"\n")
print(y , "\n" )
print(x ** y)

print('\n\n')
print("Partially Compatible","\n")
x1= np.random.randint(1 , 10 , (3,3))
y1 = np.random.randint(1 , 10 , (3))

print(x1 , "\n")
print(y1 , "\n")
print(x1 * y1 , "\n\n" , x - y)
print("\n")

print("Not Compatible","\n")
x2 = np.random.randint(1 , 10 , (3 , 2))
y2 = np.random.randint(1 , 10 , (2 , 3))

print("\n" , x2 , "\n")
print("\n" , y2 , "\n")



#DBP_NOTES as y2 and x2 has different dimension , so the solution is
#DBP_HIGHLIGHTES TRANSPOSE of y2
print("Converting y2 in its transpose MAtrix (3 * 2)" , "\n")
y3 = np.transpose(y2)
print(y3,"\n")
print("Now the operations can be possible" , "\n")
print(x2 * y3)

print("\n")

#DBP_HIGHLIGHTES Reshaping can be possible when the dimension multiplication is same
arr_reshaped = np.reshape(x2 , (2,3))
arr_reshaped



Perfectly Compatible 

[[7 6 3]
 [3 2 2]
 [7 6 3]] 

[[8 7 4]
 [4 1 4]
 [5 1 2]] 

[[5764801  279936      81]
 [     81       2      16]
 [  16807       6       9]]



Partially Compatible 

[[6 5 1]
 [9 3 1]
 [2 1 6]] 

[5 7 3] 

[[30 35  3]
 [45 21  3]
 [10  7 18]] 

 [[-1 -1 -1]
 [-1  1 -2]
 [ 2  5  1]]


Not Compatible 


 [[8 2]
 [5 7]
 [1 8]] 


 [[1 7 9]
 [4 5 8]] 

Converting y2 in its transpose MAtrix (3 * 2) 

[[1 4]
 [7 5]
 [9 8]] 

Now the operations can be possible 

[[ 8  8]
 [35 35]
 [ 9 64]]




array([[8, 2, 5],
       [7, 1, 8]])

# Practices
- ## <b style = "color:black; background:orange"> The csv is on data of terrorist attact in different country , with time , location parameters.</b>

- ## <b style = "color:black; background:white"> Importing csv in numpy </b>
- ### <b style = "color:black; background:LightGreen">  
   import csv <br>
   file_obj = open("attack.csv") <br>
   file_data = csv.DictReader(file_obj) <br>
   to show it
   for i in file_data: <br>
     print(i)
</b>

- ### <b style = "color:black; background:orange"> Storing data in array </b> <br>
 <b style = "color:black; background:LightGreen">

 ```  
     country = []
     killed =  []
     wounded = []

 ```

To show it
```
    for row in file_data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    wounded.append(row['Wounded'])

```
</b>

In [ ]:
import numpy as np
import csv  #DBP_NOTES The csv is on data of terrorist attact in different country , with time , location parameters

file_obj = open("attack.csv")
file_data = csv.DictReader(file_obj , skipinitialspace = True)


province = []
killed =  []
wounded = []


#DBP_HIGHLIGHTES To show it
for row in file_data:
    killed.append(row['Killed'])
    province.append(row['Province'])
    wounded.append(row['Wounded'])


np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_province = np.array(province)

print(np_province)

#DBP_NOTES we have to deal with missing values



np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'



#DBP_NOTES Modifying the np_killed and np_wounded so that it can deal with float values
np_killed = np.array(np_killed , dtype='float')
np_wounded = np.array(np_wounded , dtype = 'float')

killed_wounded = np_killed + np_wounded


#np_province = np_province[np_province == 'Punjab'] #Values of killed_wounded where province = Punjab

#DBP_NOTES now finding the killed_wounded where province = 'Punjab'

bool_arr = np_province == 'Punjab'
killed_wounded[bool_arr]



#DBP_HIGHLIGHTES finding the summation of killed_wounded where province = 'Punjab'

ans = killed_wounded[bool_arr]
print(np.sum(ans))

#DBP_HIGHLIGHTES finding the Summation of killed_wounded
print(np.sum(killed_wounded))

['North-West Frontier Province' 'Punjab' 'North-West Frontier Province'
 ... 'Balochistan' 'Khyber Pakhtunkhwa' 'Balochistan']
6040.0
32030.0
