In [1]:
from IPython.display import HTML

html_code = """
<h1>Feature Scaling</h1>
<h2>
<ul>
<li>It is an important preprocessing technique for regression</li>
<li>Its main goal is to transform the input
features into a range that can be easily handled by the regression algorithm.</li>
<li>It is used so that no feature can dominate or overpower other</li>
</ul>
</h2><br>
<h3>For example: f1 >> f2 in numbers</h3>
<img src="./Fscaling.png"><br><br>
<h2>Methods of doing Feature Scaling</h2>
<h2>
<ol type="1">
<li>Min Max Scaling , Making it range of [ 0 , 1 ] <br>
Suppose Xi features has X<sub>1</sub><sup>i</sup> to X<sub>m</sub><sup>i</sup> elements
<img src="./FSC2.png">
  * Subtract the minimum: X<sup>i</sup> - X<sup>i</sup><sub>min()</sub><br>
  * Subtract the minimum from maximum: X<sup>i</sup><sub>max()<?sub> -  X<sup>i</sup><sub>min()</sub><br>
  * then division: (X<sup>i</sup> - X<sup>i</sup><sub>min()</sub>) / (X<sup>i</sup><sub>max()<sub> -  X<sup>i</sup><sub>min()</sub>) <br>
</li>
<li>Min Max [ min , max ] <br>
  * Let X<sub>01</sub><sup>i</sup> = X<sup>i</sup><sub>max()<sub> -  X<sup>i</sup><sub>min()</sub><br>
  * X<sup>i</sup><sub>min max</sub> = (X<sub>01</sub><sup>i</sup>) * (max-min) + min <br>
</li> 
<li> Good Scaling Way: Standarization/Normalization <br>
X<sup>i</sup> - X<sup>i</sup><sub>mean()</sub> / standardDev[x.std()]  , mean=0 , variance=1 <br>
from sklearn import preprocessing <br>
scaler = preprocessing.StandardScaler()  <br>
scaler.fit(X) <br>
print(scaler.transform(X)) <br>
</li>
</ol>
</h2>






"""
display(HTML(html_code))

html_preprocessing = """


<h2>_ Feature scaling using Sklearn</h2>
<h2>_ Preprocessing.scale makes the data in [0,1]:</h2>
<h2>_ or in other words , it makes mean=0 , variance=1"</h2>

"""

display(HTML(html_preprocessing))


import numpy as np
from sklearn import preprocessing  
print("")
X = np.array([[1., -1., 2.],
              [2., 0., 0.],
              [0., 1.,  -1.]])

X_scaled = preprocessing.scale(X)
print("Checking mean and standard deviation")
print(X_scaled.mean(axis=0))
print(X_scaled.std(axis=0))


print("But the best way is using StandardScaler")
print("To conflict in scaling train and test dataset")
scaler = preprocessing.StandardScaler()  
scaler.fit(X) 
print(scaler.transform(X))


X_test = [[1,1,0]] #DBP_HIGHLIGHTES scaler works on 2D only , not 1D
print(scaler.transform(X_test))





Checking mean and standard deviation
[0. 0. 0.]
[1. 1. 1.]
But the best way is using StandardScaler
To conflict in scaling train and test dataset
[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
[[ 0.          1.22474487 -0.26726124]]
